from os import environ
#example code
SECRET_KEY = environ.get('SECRET_KEY')
API_KEY = environ.get('API_KEY')
SQLALCHEMY_DATABASE_URI = environ.get("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')
FLASK_ADMIN_SWATCH = 'cerulean'
FLASK_ADMIN_FLUID_LAYOUT = True
JSON_SORT_KEYS=False
JWT_SECRET_KEY = environ.get("JWT_SECRET_KEY")
RESTX_VALIDATE=True
MAIL_SERVER = environ.get('MAIL_SERVER')
MAIL_PORT = environ.get('MAIL_PORT')
MAIL_USE_TLS = environ.get('MAIL_USE_TLS')
MAIL_USERNAME = environ.get('MAIL_USERNAME')
MAIL_PASSWORD = environ.get('MAIL_PASSWORD')
SITE_NAME  = environ.get("MAIL_SENDER")
#MAIL_DEBUG=environ.get("MAIL_DEBUG")

SESSION_PERMANENT = False
SESSION_TYPE = 'sqlalchemy'
EMAIL_VERIFICATION = environ.get("EMAIL_VERIFICATION")